version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - webnet    
      - nginxnet  
      - busyboxnet  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - webnet    
      - nginxnet  

  busybox:
    image: busybox:latest
    depends_on:
      - web
    networks:
      - webnet    
      - busyboxnet  

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16  
  
  nginxnet:
    driver: bridge  
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16  
  
  busyboxnet:
    driver: bridge  
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16  
