version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "80:80"  
    depends_on:
      - web  
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
