version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Porta do host : Porta do container
    volumes:
      - .:/app  # Sincroniza os arquivos do projeto com o container
    command: python manage.py runserver 0.0.0.0:8000
